name: "Call reusable workflow"

on:
  workflow_dispatch:

jobs:
  call-greeting:
    uses: Tgelump/Github_Actions_Training/.github/workflows/Reusable Workflows.yml@cf4ced5d21033ff74fe1b9f20aabd510d69ea5f1
    with:
      actor: "User"
